language: node_js
node_js:
  - "stable"
script:
  - echo "Deploying!"
install:
    - npm install -g firebase-tools 
deploy:
  provider: firebase
  token: 
    secure: 
  project: "questions-veselov"
  after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  